#ifndef HW_MISC_LINQU_UB_REGS_H
#define HW_MISC_LINQU_UB_REGS_H

#define LINQU_UB_MMIO_REGION_SIZE      0x4000
#define LINQU_UB_ENDPOINT_BASE         0x1000
#define LINQU_UB_ENDPOINT_STRIDE       0x100

#define LINQU_UB_REG_VERSION           0x00
#define LINQU_UB_REG_FEATURES          0x08

#define LINQU_UB_REG_CMDQ_BASE_LO      0x10
#define LINQU_UB_REG_CMDQ_BASE_HI      0x18
#define LINQU_UB_REG_CMDQ_SIZE         0x20
#define LINQU_UB_REG_CMDQ_HEAD         0x28
#define LINQU_UB_REG_CMDQ_TAIL         0x30

#define LINQU_UB_REG_CQ_BASE_LO        0x38
#define LINQU_UB_REG_CQ_BASE_HI        0x40
#define LINQU_UB_REG_CQ_SIZE           0x48
#define LINQU_UB_REG_CQ_HEAD           0x50
#define LINQU_UB_REG_CQ_TAIL           0x58

#define LINQU_UB_REG_STATUS            0x60
#define LINQU_UB_REG_DOORBELL          0x68
#define LINQU_UB_REG_LAST_ERROR        0x70
#define LINQU_UB_REG_IRQ_STATUS        0x78
#define LINQU_UB_REG_IRQ_ACK           0x80

#define LINQU_UB_DESC_BYTES            64
#define LINQU_UB_MAX_ENDPOINTS         16
#define LINQU_UB_DEFAULT_CMDQ_DEPTH    32
#define LINQU_UB_DEFAULT_CQ_DEPTH      64

#define LINQU_UB_IRQ_COMPLETION        (1u << 0)
#define LINQU_UB_IRQ_ERROR             (1u << 1)
#define LINQU_UB_IRQ_CQ_OVERFLOW       (1u << 2)

#define LINQU_UB_STATUS_CMDQ_PENDING_SHIFT  0
#define LINQU_UB_STATUS_CQ_PENDING_SHIFT    16
#define LINQU_UB_STATUS_CMDQ_HEAD_SHIFT     32
#define LINQU_UB_STATUS_CMDQ_TAIL_SHIFT     40
#define LINQU_UB_STATUS_CQ_HEAD_SHIFT       48
#define LINQU_UB_STATUS_CQ_TAIL_SHIFT       56

enum LinquUbErrorCode {
    LINQU_UB_ERR_NONE = 0,
    LINQU_UB_ERR_INVALID_REGISTER_WRITE = 1,
    LINQU_UB_ERR_INVALID_REGISTER_READ = 2,
    LINQU_UB_ERR_INVALID_OFFSET = 3,
    LINQU_UB_ERR_ENDPOINT_NOT_FOUND = 4,
    LINQU_UB_ERR_QUEUE_OVERFLOW = 5,
    LINQU_UB_ERR_RANGE = 6,
    LINQU_UB_ERR_INVALID_DESCRIPTOR = 7,
    LINQU_UB_ERR_NOT_IMPLEMENTED = 8,
};

#endif
